---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      avalonia:
        patterns:
          - "^Avalonia.*"
      serilog:
        patterns:
          - "^Serilog.*"
      testing:
        patterns:
          - "^FluentAssertions"
          - "^Microsoft.NET.Test.Sdk"
          - "^xunit.*"
          - "^coverlet.collector"
