---
version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      autofac:
        patterns:
          - "^Autofac"
          - "^Autofac.*"
      avalonia:
        patterns:
          - "^Avalonia"
          - "^Avalonia.*"
      serilog:
        patterns:
          - "^Serilog"
          - "^Serilog.*"
      testing:
        patterns:
          - "^FluentAssertions"
          - "^Microsoft.NET.Test.Sdk"
          - "^xunit"
          - "^xunit.*"
          - "^coverlet.collector"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
