<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <PublishSingleFile Condition="'$(Configuration)' != 'Debug'">true</PublishSingleFile>
        <SelfContained Condition="'$(Configuration)' != 'Debug'">true</SelfContained>


        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />

        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../BaldersGait.Core/BaldersGait.Core.csproj" />
    </ItemGroup>
</Project>
