name: .NET Build

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      # Test
      - name: Unit Tests
        run: |
          dotnet build --no-incremental
          dotnet test

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # Setup
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      # Build
      - name: Build
        run: |
          dotnet publish --configuration Release --runtime linux-x64 --property PublishDir=~/publish

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: BaldersGait-linux-x64
          path: ~/publish

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      # Setup
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Environment
        uses: ./.github/actions/setup-env

      # Build
      - name: Build
        run: |
          dotnet publish  --configuration Release --runtime win-x64 --property PublishDir=publish

      # Upload
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: BaldersGait-win-x64
          path: D:\a\BaldersGait\BaldersGait\BaldersGait\publish\