name: .NET Build

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "*"

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Build
      - name: Build
        run: |
          dotnet build
  
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#      # Setup
#      - name: Checkout Repo
#        uses: actions/checkout@v3
#      - name: Setup .NET
#        uses: actions/setup-dotnet@v3
#        with:
#          dotnet-version: ${{ env.DOTNET_VERSION }}
#      
#      # Build
#      - name: Test
#        run: |
#          dotnet test /p:CollectCoverage=true --collect:"XPlat Code Coverage;Format=opencover"
#